[package]
name = "rust-mouse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version="0.2", features=["time","macros"] }
mouse-rs = "0.4"
keepawake = "0.4.5"
rand = "0.8.0"
